# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dZoCUC32jQTU3_NFRq4QRZwww42tYsd
"""

import pandas as pd
from pathlib import Path

def load_data(file_path):
    """
    Load CSV into a pandas DataFrame.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {file_path}")
    df = pd.read_csv(path)
    print(f"[data_loader] Loaded {file_path} with shape {df.shape}")
    return df

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="../data/sample.csv")
    args = parser.parse_args()
    df = load_data(args.input)
    print(df.head())